### PR TITLE
Fix for compatibility with older python version

### PR DESCRIPTION
**Pull request by bilbolodz**
Replaced format function with old formatting style. Checked with python 2.6.

### CODE REVIEW

**Comment by bilbolodz** [comment]
Are you going to integrate my changes into your code or should I try to merge your 9.1 changes into "my code" and leave it as a fork?

**Comment by Spindel** [comment]
I'm looking at this, and since this code isn't a complete conversion, `foreach_db` and a few others still use `.format` syntax, I'd say that you probably should keep it as a fork.

I've pushed your changes  to the branch `python-26-partial` for now

**Comment by Spindel** [comment]
https://github.com/Spindel/PgZabbix/tree/python-26-partial

**Comment by bilbolodz** [comment]
I've checked it. Code is working on python 2.6. Now I've realized that instead rewriting to "$d %" old format it should be enough to put positional argument into brackets:

"Changed in version 2.7: The positional argument specifiers can be omitted, so '{} {}' is equivalent to '{0} {1}'."
https://docs.python.org/2/library/string.html#format-string-syntax 

So I think if you wish you can integrate it into main branch.

**Comment by Spindel** [comment]
That seems like a better change, yes.
That means that the `"{first} {second}".format(**args)` will work as
intended too.

I'll fix that up on the branch and let you test it.

**Comment by bilbolodz** [comment]
Your are right. It's probabbly better way. I've checked more thoroughly and it turned out that on python 2.7 there are errors:

root@csa:~# /usr/bin/python /usr/local/lib/pgzabbix-1.8.linux-x86_64.zip --read
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/__main__.py", line 1, in <module>
  File "/pgzabbix/__init__.py", line 2, in <module>
  File "/usr/local/lib/pgzabbix-1.8.linux-x86_64.zip/pgzabbix/generic.py", line 89
    " and current_query ~* '^(insert|update|delete)'") limit
                                                           ^
SyntaxError: invalid syntax

So I'm waiting for new version to test.

**Comment by bilbolodz** [comment]
Confirmed, that code:

a="fisrt"
b="second"
out="F: {0} S:{1}"
print out.format(a,b)

works on python 2.6 and 2.7

**Comment by Spindel** [comment]
Then let's try this change instead:
https://github.com/Spindel/PgZabbix/tree/old-style-format

**Comment by bilbolodz** [comment]
Test in progress....

**Comment by bilbolodz** [comment]
It's working checked on python 2.6 and 2.7, Ubuntu 10.10, 12.04, 14.04, 16.04 and postgres version: 9.1.9, 9.4.1, 9.5.8.

**Comment by Spindel** [comment]
Thank you, I've merged that to master now. Closing this MR!

**Pull request closed without merging**
